# Generated by Django 6.0.7 on 2026-07-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
